# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/baho/MapWidget

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/baho/MapWidget

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baho/MapWidget/CMakeFiles /home/baho/MapWidget//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baho/MapWidget/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MapWidget

# Build rule for target.
MapWidget: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MapWidget
.PHONY : MapWidget

# fast build rule for target.
MapWidget/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/build
.PHONY : MapWidget/fast

#=============================================================================
# Target rules for targets named MapWidget_autogen

# Build rule for target.
MapWidget_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MapWidget_autogen
.PHONY : MapWidget_autogen

# fast build rule for target.
MapWidget_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget_autogen.dir/build.make CMakeFiles/MapWidget_autogen.dir/build
.PHONY : MapWidget_autogen/fast

MapWidget_autogen/mocs_compilation.o: MapWidget_autogen/mocs_compilation.cpp.o
.PHONY : MapWidget_autogen/mocs_compilation.o

# target to build an object file
MapWidget_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/MapWidget_autogen/mocs_compilation.cpp.o
.PHONY : MapWidget_autogen/mocs_compilation.cpp.o

MapWidget_autogen/mocs_compilation.i: MapWidget_autogen/mocs_compilation.cpp.i
.PHONY : MapWidget_autogen/mocs_compilation.i

# target to preprocess a source file
MapWidget_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/MapWidget_autogen/mocs_compilation.cpp.i
.PHONY : MapWidget_autogen/mocs_compilation.cpp.i

MapWidget_autogen/mocs_compilation.s: MapWidget_autogen/mocs_compilation.cpp.s
.PHONY : MapWidget_autogen/mocs_compilation.s

# target to generate assembly for a file
MapWidget_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/MapWidget_autogen/mocs_compilation.cpp.s
.PHONY : MapWidget_autogen/mocs_compilation.cpp.s

drone.o: drone.cpp.o
.PHONY : drone.o

# target to build an object file
drone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/drone.cpp.o
.PHONY : drone.cpp.o

drone.i: drone.cpp.i
.PHONY : drone.i

# target to preprocess a source file
drone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/drone.cpp.i
.PHONY : drone.cpp.i

drone.s: drone.cpp.s
.PHONY : drone.s

# target to generate assembly for a file
drone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/drone.cpp.s
.PHONY : drone.cpp.s

dronemanager.o: dronemanager.cpp.o
.PHONY : dronemanager.o

# target to build an object file
dronemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/dronemanager.cpp.o
.PHONY : dronemanager.cpp.o

dronemanager.i: dronemanager.cpp.i
.PHONY : dronemanager.i

# target to preprocess a source file
dronemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/dronemanager.cpp.i
.PHONY : dronemanager.cpp.i

dronemanager.s: dronemanager.cpp.s
.PHONY : dronemanager.s

# target to generate assembly for a file
dronemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/dronemanager.cpp.s
.PHONY : dronemanager.cpp.s

mapWidget.o: mapWidget.cpp.o
.PHONY : mapWidget.o

# target to build an object file
mapWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/mapWidget.cpp.o
.PHONY : mapWidget.cpp.o

mapWidget.i: mapWidget.cpp.i
.PHONY : mapWidget.i

# target to preprocess a source file
mapWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/mapWidget.cpp.i
.PHONY : mapWidget.cpp.i

mapWidget.s: mapWidget.cpp.s
.PHONY : mapWidget.s

# target to generate assembly for a file
mapWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/mapWidget.cpp.s
.PHONY : mapWidget.cpp.s

tile.o: tile.cpp.o
.PHONY : tile.o

# target to build an object file
tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/tile.cpp.o
.PHONY : tile.cpp.o

tile.i: tile.cpp.i
.PHONY : tile.i

# target to preprocess a source file
tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/tile.cpp.i
.PHONY : tile.cpp.i

tile.s: tile.cpp.s
.PHONY : tile.s

# target to generate assembly for a file
tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/tile.cpp.s
.PHONY : tile.cpp.s

tileManager.o: tileManager.cpp.o
.PHONY : tileManager.o

# target to build an object file
tileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/tileManager.cpp.o
.PHONY : tileManager.cpp.o

tileManager.i: tileManager.cpp.i
.PHONY : tileManager.i

# target to preprocess a source file
tileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/tileManager.cpp.i
.PHONY : tileManager.cpp.i

tileManager.s: tileManager.cpp.s
.PHONY : tileManager.s

# target to generate assembly for a file
tileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MapWidget.dir/build.make CMakeFiles/MapWidget.dir/tileManager.cpp.s
.PHONY : tileManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MapWidget_autogen"
	@echo "... MapWidget"
	@echo "... MapWidget_autogen/mocs_compilation.o"
	@echo "... MapWidget_autogen/mocs_compilation.i"
	@echo "... MapWidget_autogen/mocs_compilation.s"
	@echo "... drone.o"
	@echo "... drone.i"
	@echo "... drone.s"
	@echo "... dronemanager.o"
	@echo "... dronemanager.i"
	@echo "... dronemanager.s"
	@echo "... mapWidget.o"
	@echo "... mapWidget.i"
	@echo "... mapWidget.s"
	@echo "... tile.o"
	@echo "... tile.i"
	@echo "... tile.s"
	@echo "... tileManager.o"
	@echo "... tileManager.i"
	@echo "... tileManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

